src/data_manager.cpp
src/tests/test_repeated_runs.py
src/tests/test_vgf_graph.py
src/tests/test_vgf_shader.py

Change-Id: I0ca81472d784177a1360ca68a166f4ca4da62339

Use vgf lib verify functions

---

README.md

Change-Id: I40ddd0d3f8b15278a45986ca7e4bca2f4a0e38fe

Update flatc instructions in docs

---

src/pipeline_cache.cpp
src/pipeline_cache.hpp
src/tests/test_pipeline_cache.py

Initial pipeline cache validation
utilizing header data and max cache size
Change-Id: I2c61b80a72f4b8de1b7b855fc308946c27682778

Add pipeline cache validation

---

docs/source/cloning.rst

Change-Id: I94176af3f788099047aa6fb011c6c9110609e52b

Add url to manifest

---

src/dds_reader.cpp
src/dds_reader.hpp
src/tests/resources/scenarios/test_dds/passthrough_sampler_R16.json
src/tests/resources/shaders/test_dds/passthrough_glsl_sampler_R16.comp
src/tests/test_dds.py
src/tools/dds_utils/main.cpp

Change-Id: I5cda29508e1b0dd863d35e541a264cdd1ff54c98

Add R16 float support to Images

---

src/barrier.cpp
src/barrier.hpp
src/main.cpp
src/pipeline.cpp
src/pipeline.hpp
src/resource_desc.cpp
src/resource_desc.hpp
src/scenario.cpp
src/scenario.hpp
src/tests/conftest.py

Remove redundant static
Remove redundant set of member
Remove redundant members in derived struct
Remove unused member
Remove debug logging to stderr
Change-Id: Idcefb93caaa087bd6421a5277ec41bbf4dac495f

Move arguments and some code polish

---

src/main.cpp
src/scenario.cpp
src/scenario.hpp

Change-Id: I9fb904c22dda2a0d42ef3c146d8499e44b52c73c

Arguments by reference

---

docs/source/cloning.rst

Change-Id: I7440d68b2c72754dcad2604da201e0a4d040f664

Update cloning instruction

---

README.md
docs/docs.cmake
docs/source/conf.py

Change-Id: Ieba9b5b88e27546b98d21503fa1959953b33a4b9

Suppress unwanted doc build warnings and fail on new warnings

---

src/numpy.cpp
src/numpy.hpp
src/pipeline.cpp
src/pipeline.hpp
src/raw_data.cpp
src/raw_data.hpp
src/scenario.cpp
src/scenario.hpp
src/tensor.cpp
src/tests/numpy_test.cpp
src/utils.cpp

Align naming of member variables.
Move code into implementation.
Change-Id: I1844de9dae385c091316e20f3674c29780b75193

Delete obsolete code

---

src/data_manager.cpp
src/json_reader.cpp
src/resource_desc.cpp
src/resource_desc.hpp
src/scenario.cpp
src/scenario.hpp
src/utils.cpp

Resolve paths internally in ScenarioSpec.
Remove sub class src member hiding base class
optional. This caused inconsistent code.
Change-Id: I53bb26d7ba00b1f2bd4c0da748849822affdeaad

Simplify json parsing of resources

---

src/data_manager.cpp
src/data_manager.hpp
src/image.cpp
src/image.hpp
src/tensor.cpp
src/tensor.hpp
src/tests/json_parser_tests.cpp
src/vgf_view.cpp
src/vgf_view.hpp

Return const reference to map.
Create help function for calculating buffer size.
Make image identifiers unique.
Change-Id: I3e6e3301e1d0c9c309176dd2aa96c975e3899193

Move private static functions to implementation

---

README.md
docs/source/cloning.rst
docs/source/index.rst

Change-Id: Ibd019a0e4e2cbee02c11f1036b7dc21f805ec39f

Move cloning instructions to README

---

src/compute.hpp
src/scenario.cpp
src/scenario_desc.cpp
src/scenario_desc.hpp

Change-Id: Ib2c49dd86895f26ae697cc0b6656eff32a04d47f

Simplify frameId offset calculation for mark boundaries

---

src/commands.hpp
src/compute.cpp
src/compute.hpp
src/data_manager.cpp
src/data_manager.hpp
src/pipeline.cpp
src/pipeline.hpp
src/scenario.cpp
src/scenario.hpp
src/tests/vulkan_startup_tests.cpp

Resolve type info in Scenario to simplify other classes.
Change-Id: Iabd50fe44020d7a579cc2ae0b0b7f071c65367cc

Refactor getDescriptorType handling

---

src/barrier.hpp
src/data_manager.hpp
src/dds_reader.hpp
src/iresource.hpp
src/main.cpp
src/scenario.cpp
src/types.hpp
src/vgf_view.cpp
src/vgf_view.hpp

Avoid exposing Context dependency and remove
unused include.
Remove unused type.
Modernize typedef
Change-Id: I9654c5c1f623b10de58fd50692907d726cde0b82

Add api for resource creation

---

src/compute.cpp
src/compute.hpp
src/scenario.cpp
src/scenario.hpp
src/tests/vulkan_startup_tests.cpp
src/types.hpp

Create new structs that contain parsed and verified data.
Change-Id: Iab103406553be04f579ce1f4d1ae2b5e68f165b9

Create new data structs for commands

---

pip_package/pyproject.toml
pip_package/scenario_runner/__init__.py
pip_package/scenario_runner/cli.py
pip_package/setup.py
scripts/build.py

Change-Id: I9483d9d76f656bca8b281d4b2c140c6218227659

Add pip packaging support

---

src/compute.cpp
src/compute.hpp
src/scenario.cpp

Clear all members of Compute
Merge and use private functions.
Change-Id: Iab084a69992a7c5878e6186609817192f4eecfe3

Refactor Compute object handling

---

src/scenario.cpp

Fix image layout reset that was wrongly moved.
Change-Id: I581f65f6fee70d210763eafae0e27ec5c6e08f64

Handle image layout

---

src/compute.cpp
src/compute.hpp
src/pipeline.cpp
src/pipeline.hpp
src/vgf_view.cpp
src/vgf_view.hpp

Avoid repeating types.
Change-Id: I4d1c251b49956837765716e0c948bf920a9e0d2b

Create helper functions.

---

pip_package/setup.py

Change-Id: Ice7d68a1a19c734ca369240a6fa47d83e41fa95b

Rename pip package

---

src/CMakeLists.txt
src/compute.cpp
src/compute.hpp
src/iresource.cpp
src/iresource.hpp
src/tests/CMakeLists.txt
src/tests/iresource_tests.cpp
src/vgf_view.cpp
src/vgf_view.hpp

Create base implementation for resource viewer.
Prepare for other resource manager.
Change-Id: I930968982ee48b01b7b2c32fc20eb8b3c2741d00

Create api used internally for getting resource

---

src/compute.cpp
src/compute.hpp
src/pipeline.cpp
src/pipeline.hpp
src/scenario.cpp
src/tests/vulkan_startup_tests.cpp

Create struct to hold common arguments for pipeline creation. Add const
Change-Id: Ib65b7bfa56d668a8ee34fd217f79b947e7cbac81

Create helper functions and add struct

---

src/buffer.hpp
src/data_manager.hpp
src/image.cpp
src/pipeline.cpp
src/pipeline.hpp
src/resource_desc.cpp
src/resource_desc.hpp
src/scenario.cpp
src/tests/vulkan_startup_tests.cpp
src/types.hpp
src/utils.cpp
src/utils.hpp

Create new type to avoid using the json descriptor. Decouple Pipeline class from json related types.
Clean up includes.
Change-Id: I52f4fca6b55ad4030bc4281b9803280b530f743b

Add new ShaderInfo type

---

requirements.txt
tooling-requirements.txt

Input from SBOM and docker build log
Change-Id: Ic90586c4ba664f0d79296d1e1ca5c18f392daa37

Fix requirement versions

---

src/tests/json/resources/image/invalid_border_address_mode.json
src/tests/json/resources/image/invalid_border_color.json
src/tests/json/resources/image/invalid_dim_value.json
src/tests/json/resources/image/invalid_mag_filter.json
src/tests/json/resources/image/invalid_min_filter.json
src/tests/json/resources/image/invalid_mip_filter.json
src/tests/json/resources/image/invalid_mips.json
src/tests/json/resources/image/invalid_property.json
src/tests/json/resources/image/invalid_shader_access.json
src/tests/json/resources/image/minimal.json
src/tests/json/resources/image/missing_format.json
src/tests/json/resources/image/missing_shader_access.json
src/tests/json/resources/image/missing_uid.json
src/tests/json/resources/image/mutually_exclusive_src_dst.json
src/tests/json/resources/image/reference.json

Change-Id: Ie726266594d9fe91965a83fa4ec55748dbf422c3

Update test scenario images to be 4D

---

.pre-commit-config.yaml

Change-Id: I1a23888bbfed8df624442424c18364a174e0b20d

Removing prettier pre-commit hook

---

ai-ml-sdk-scenario-runner.spdx.json
cmake/package.cmake
scripts/build.py

Change-Id: I63d1dc8813f98df5bc5652e5514e8ceb39d1a1f8

Add SBOM file

---

pip_package/setup.py

Change-Id: Ide26d76a56fc58e879cdb4a6725c13c42fe01066

Fix for pip packaging

---

RELEASE_NOTES.md

Change-Id: I66b75173fcfbd781a299783ca569ccc186c35d88

Add initial release note

---

RELEASE_NOTES.md

Change-Id: I36ca25e1cecb198ccf9527c4211a82a279b7149e

Align release note format

---

scripts/build.py

Change-Id: Ia906af9fc53a6fe69595895ddbc8686280ec9fca

Fix missing package version initialisation in build script
